### ISSUE TITLE
question

### ISSUE THREAD

**Issue by littlealili** [hmshan/MAP-NN#2]
why"No module named 'pydicom'"?
![QQ截图20190916164006](https://user-images.githubusercontent.com/52142643/64944299-a704fe00-d8a0-11e9-85fc-9aa20f10dde9.png)

**Comment by hmshan** [comment]
Please have the pydicom installed on your computer. More informaiton about how to install and use the pydicom can be found here https://pydicom.github.io/pydicom/stable/getting_started.html. Thanks.
